# Machine Learning CSE4020 L9+L10
## Proff. Sharmila Banu K.
### Sahaj Adlakha (18BCE0054)
Theory Slot - F2

### LAB TASK 1 - Simple Binary Classification

In [79]:
import sklearn.datasets
import numpy as np

In [80]:
cancer_ds = sklearn.datasets.load_breast_cancer()

In [81]:
# Organising X and Y
X = cancer_ds.data
Y = cancer_ds.target

In [82]:
print(X)

[[1.799e+01 1.038e+01 1.228e+02 ... 2.654e-01 4.601e-01 1.189e-01]
 [2.057e+01 1.777e+01 1.329e+02 ... 1.860e-01 2.750e-01 8.902e-02]
 [1.969e+01 2.125e+01 1.300e+02 ... 2.430e-01 3.613e-01 8.758e-02]
 ...
 [1.660e+01 2.808e+01 1.083e+02 ... 1.418e-01 2.218e-01 7.820e-02]
 [2.060e+01 2.933e+01 1.401e+02 ... 2.650e-01 4.087e-01 1.240e-01]
 [7.760e+00 2.454e+01 4.792e+01 ... 0.000e+00 2.871e-01 7.039e-02]]


In [83]:
print(Y)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 1 0 0 0 0 0 0 0 0 1 0 1 1 1 1 1 0 0 1 0 0 1 1 1 1 0 1 0 0 1 1 1 1 0 1 0 0
 1 0 1 0 0 1 1 1 0 0 1 0 0 0 1 1 1 0 1 1 0 0 1 1 1 0 0 1 1 1 1 0 1 1 0 1 1
 1 1 1 1 1 1 0 0 0 1 0 0 1 1 1 0 0 1 0 1 0 0 1 0 0 1 1 0 1 1 0 1 1 1 1 0 1
 1 1 1 1 1 1 1 1 0 1 1 1 1 0 0 1 0 1 1 0 0 1 1 0 0 1 1 1 1 0 1 1 0 0 0 1 0
 1 0 1 1 1 0 1 1 0 0 1 0 0 0 0 1 0 0 0 1 0 1 0 1 1 0 1 0 0 0 0 1 1 0 0 1 1
 1 0 1 1 1 1 1 0 0 1 1 0 1 1 0 0 1 0 1 1 1 1 0 1 1 1 1 1 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 1 1 1 1 1 1 0 1 0 1 1 0 1 1 0 1 0 0 1 1 1 1 1 1 1 1 1 1 1 1
 1 0 1 1 0 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 0 1 0 1 1 1 1 0 0 0 1 1
 1 1 0 1 0 1 0 1 1 1 0 1 1 1 1 1 1 1 0 0 0 1 1 1 1 1 1 1 1 1 1 1 0 0 1 0 0
 0 1 0 0 1 1 1 1 1 0 1 1 1 1 1 0 1 1 1 0 1 1 0 0 1 1 1 1 1 1 0 1 1 1 1 1 1
 1 0 1 1 1 1 1 0 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 0 1 0 0 1 0 1 1 1 1 1 0 1 1
 0 1 0 1 1 0 1 0 1 1 1 1 1 1 1 1 0 0 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 0 1
 1 1 1 1 1 1 0 1 0 1 1 0 

In [84]:
print(X.shape, Y.shape)

(569, 30) (569,)


In [85]:
# Get The data into a dataframe
import pandas as pd
data = pd.DataFrame(cancer_ds.data, columns=cancer_ds.feature_names)


In [86]:
# REname the target Variable
data['class'] = cancer_ds.target

In [87]:
data.head()

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   mean fractal dimension  ...  worst texture  worst perimeter  worst area  \
0                 0.07871  ...          17.33           184.60      2019.0   
1                 0.05667  ...          23.41           158.80      1956.0   
2                 0.05999  ...          25.53           152.50      1709.0   
3                 0.09744  ...          26.50            98.87       567.7   
4                 0.05883  ...          16.67           152.20      1575.0   

   worst smoothness  worst compactness  worst concavity  worst concave points  \
0            0.1622             0.6656           0.7119                0.2654   
1            0.1238             0.1866           0.2416                0.1860   
2            0.1444             0.4245           0.4504                0.2430   
3            0.2098             0.8663           0.6869                0.2575   
4            0.1374             0.2050           0.4000                0.1625   

   worst symmetry  worst fractal dimension  class  
0          0.4601                  0.11890      0  
1          0.2750                  0.08902      0  
2          0.3613                  0.08758      0  
3          0.6638                  0.17300      0  
4          0.2364                  0.07678      0  

[5 rows x 31 columns]

In [88]:
data.describe()

mean radius  mean texture  mean perimeter    mean area  \
count   569.000000    569.000000      569.000000   569.000000   
mean     14.127292     19.289649       91.969033   654.889104   
std       3.524049      4.301036       24.298981   351.914129   
min       6.981000      9.710000       43.790000   143.500000   
25%      11.700000     16.170000       75.170000   420.300000   
50%      13.370000     18.840000       86.240000   551.100000   
75%      15.780000     21.800000      104.100000   782.700000   
max      28.110000     39.280000      188.500000  2501.000000   

       mean smoothness  mean compactness  mean concavity  mean concave points  \
count       569.000000        569.000000      569.000000           569.000000   
mean          0.096360          0.104341        0.088799             0.048919   
std           0.014064          0.052813        0.079720             0.038803   
min           0.052630          0.019380        0.000000             0.000000   
25%           0.086370          0.064920        0.029560             0.020310   
50%           0.095870          0.092630        0.061540             0.033500   
75%           0.105300          0.130400        0.130700             0.074000   
max           0.163400          0.345400        0.426800             0.201200   

       mean symmetry  mean fractal dimension  ...  worst texture  \
count     569.000000              569.000000  ...     569.000000   
mean        0.181162                0.062798  ...      25.677223   
std         0.027414                0.007060  ...       6.146258   
min         0.106000                0.049960  ...      12.020000   
25%         0.161900                0.057700  ...      21.080000   
50%         0.179200                0.061540  ...      25.410000   
75%         0.195700                0.066120  ...      29.720000   
max         0.304000                0.097440  ...      49.540000   

       worst perimeter   worst area  worst smoothness  worst compactness  \
count       569.000000   569.000000        569.000000         569.000000   
mean        107.261213   880.583128          0.132369           0.254265   
std          33.602542   569.356993          0.022832           0.157336   
min          50.410000   185.200000          0.071170           0.027290   
25%          84.110000   515.300000          0.116600           0.147200   
50%          97.660000   686.500000          0.131300           0.211900   
75%         125.400000  1084.000000          0.146000           0.339100   
max         251.200000  4254.000000          0.222600           1.058000   

       worst concavity  worst concave points  worst symmetry  \
count       569.000000            569.000000      569.000000   
mean          0.272188              0.114606        0.290076   
std           0.208624              0.065732        0.061867   
min           0.000000              0.000000        0.156500   
25%           0.114500              0.064930        0.250400   
50%           0.226700              0.099930        0.282200   
75%           0.382900              0.161400        0.317900   
max           1.252000              0.291000        0.663800   

       worst fractal dimension       class  
count               569.000000  569.000000  
mean                  0.083946    0.627417  
std                   0.018061    0.483918  
min                   0.055040    0.000000  
25%                   0.071460    0.000000  
50%                   0.080040    1.000000  
75%                   0.092080    1.000000  
max                   0.207500    1.000000  

[8 rows x 31 columns]

In [89]:
print(data['class'].value_counts())

1    357
0    212
Name: class, dtype: int64


In [90]:
print(cancer_ds.target_names)

['malignant' 'benign']


In [91]:
print(data.groupby('class').mean())

       mean radius  mean texture  mean perimeter   mean area  mean smoothness  \
class                                                                           
0        17.462830     21.604906      115.365377  978.376415         0.102898   
1        12.146524     17.914762       78.075406  462.790196         0.092478   

       mean compactness  mean concavity  mean concave points  mean symmetry  \
class                                                                         
0              0.145188        0.160775             0.087990       0.192909   
1              0.080085        0.046058             0.025717       0.174186   

       mean fractal dimension  ...  worst radius  worst texture  \
class                          ...                                
0                    0.062680  ...     21.134811      29.318208   
1                    0.062867  ...     13.379801      23.515070   

       worst perimeter   worst area  worst smoothness  worst compactness  \
class        

## Train Test Split

In [92]:
from sklearn.model_selection import train_test_split

In [93]:
X = data.drop('class', axis=1)
Y = data['class']

In [94]:
type(X)

pandas.core.frame.DataFrame

In [95]:
# Splitting the dataset
X_train, X_test, Y_train, Y_test = train_test_split(X, Y)
# X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.1)

In [96]:
print(Y.shape, Y_train.shape, Y_test.shape)

(569,) (426,) (143,)


Lab 4


In [97]:
# Stratify param - tries to divide the positives and negatives(in this case as 'Y' is passed as the value for the stratify param) proportionaly (even) among test and train dataset

# In this context, stratification means that the train_test_split method returns training and test subsets that have the same proportions of class labels as the input dataset.
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.1, stratify = Y)


In [98]:
print(Y.shape, Y_train.shape, Y_test.shape)


(569,) (512,) (57,)


In [99]:
print(X_train.mean(), X_test.mean(), X.mean())


mean radius                 14.153645
mean texture                19.272109
mean perimeter              92.161816
mean area                  658.339648
mean smoothness              0.096439
mean compactness             0.104928
mean concavity               0.089360
mean concave points          0.049209
mean symmetry                0.180910
mean fractal dimension       0.062827
radius error                 0.409726
texture error                1.212468
perimeter error              2.894126
area error                  41.044080
smoothness error             0.007089
compactness error            0.025641
concavity error              0.032242
concave points error         0.011871
symmetry error               0.020497
fractal dimension error      0.003825
worst radius                16.312684
worst texture               25.660039
worst perimeter            107.560820
worst area                 887.789648
worst smoothness             0.132537
worst compactness            0.254607
worst concav

In [100]:
# Random_state param

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.1, stratify = Y, random_state=10)


Random_state can be 0 or 1 or any other integer. It should be the same value if you want to validate your processing over multiple runs of the code. 

the random_state parameter is used for initializing the internal random number generator, which will decide the splitting of data into train and test indices in your case.

If random_state is None or np.random, then a randomly-initialized RandomState object is returned.

If random_state is an integer, then it is used to seed a new RandomState object.

This is to check and validate the data when running the code multiple times. Setting random_state a fixed value will guarantee that the same sequence of random numbers is generated each time you run the code.

In [101]:
# Mean of each of the features of the following sets
print(X_train.mean(), X_test.mean(), X.mean())

mean radius                 14.119902
mean texture                19.275898
mean perimeter              91.879395
mean area                  654.603711
mean smoothness              0.096161
mean compactness             0.103251
mean concavity               0.087585
mean concave points          0.048536
mean symmetry                0.181293
mean fractal dimension       0.062691
radius error                 0.403297
texture error                1.218786
perimeter error              2.849795
area error                  40.127699
smoothness error             0.007072
compactness error            0.025176
concavity error              0.031683
concave points error         0.011771
symmetry error               0.020537
fractal dimension error      0.003751
worst radius                16.233904
worst texture               25.619766
worst perimeter            106.947520
worst area                 877.067188
worst smoothness             0.131886
worst compactness            0.250044
worst concav

In [102]:
# * HW explore one more argument and analyse its use

## Binarised Input

pd.cut will take care of a threshold value for every column and will assign the given labels to it

Bin values into discrete intervals.

Use cut when you need to segment and sort data values into bins. This function is also useful for going from a continuous variable to a categorical variable. For example, cut could convert ages to groups of age ranges. Supports binning into an equal number of bins, or a pre-specified array of bins.

In [103]:
X_binarised_train= X_train.apply(pd.cut, bins = 2, labels = [1,0]) #(labels = [1,0]) != ([0,1])
X_binarised_train_01= X_train.apply(pd.cut, bins = 2, labels = [0,1]) #(labels = [1,0]) != ([0,1])

In [104]:
print(X_train.head())
print(X_binarised_train.head())
print(X_binarised_train_01.head())

     mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
535        20.55         20.86          137.80     1308.0          0.10460   
338        10.05         17.53           64.41      310.8          0.10070   
503        23.09         19.83          152.10     1682.0          0.09342   
26         14.58         21.53           97.41      644.8          0.10540   
158        12.06         12.74           76.84      448.6          0.09311   

     mean compactness  mean concavity  mean concave points  mean symmetry  \
535           0.17390         0.20850              0.13220         0.2127   
338           0.07326         0.02511              0.01775         0.1890   
503           0.12750         0.16760              0.10030         0.1505   
26            0.18680         0.14250              0.08783         0.2252   
158           0.05241         0.01972              0.01963         0.1590   

     mean fractal dimension  ...  worst radius  worst texture  \
535

In [105]:
X_binarised_test = X_test.apply(pd.cut, bins = 2, labels = [1,0])
print(X_binarised_test.head())

    mean radius mean texture mean perimeter mean area mean smoothness  \
563           0            0              0         0               0   
347           1            1              1         1               1   
44            1            0              1         1               1   
289           1            1              1         1               1   
424           1            1              1         1               0   

    mean compactness mean concavity mean concave points mean symmetry  \
563                0              0                   0             0   
347                1              1                   1             1   
44                 1              1                   1             1   
289                1              1                   1             0   
424                1              1                   1             0   

    mean fractal dimension  ... worst radius worst texture worst perimeter  \
563                      0  ...            0

In [106]:
# converting to array
X_binarised_train = X_binarised_train.values
X_binarised_test = X_binarised_test.values
type(X_binarised_test)

numpy.ndarray

## ML MODEL

In [107]:
import random

In [109]:
b = 10 
# Just trying on a random row
i= random.randint(0,X_train.shape[0])
print('Row number: ', i)
if np.sum(X_binarised_train[i,:]) >= b :
    print('ML Model says its Malignant')
else:
    print('ML Model says its Benign')

if Y_train[i] == 1:
    print('Actual Output -> Malignant')
else:
    print('Actual Output -> Benign')


Row number:  442
ML Model says its Malignant
Actual Output -> Malignant


In [110]:
Y_train = Y_train.values

In [77]:
def accuracy(b,Y_train, X_binarised_train):
    accuratePredictedValues = 0 # stores the count of correctly predicted cases
    for x in range(0, Y_train.shape[0]):
        if np.sum(X_binarised_train[x,:]) >= b and Y_train[x] == 1:
            accuratePredictedValues += 1
        elif np.sum(X_binarised_train[x,:]) < b and Y_train[x] == 0:
            accuratePredictedValues += 1

    return(accuratePredictedValues/Y_train.shape[0])


In [78]:
for b in range(0,X_train.shape[1]):
    print('Value of b : ',b)
    print('Accuracy: ',accuracy(b, Y_train, X_binarised_train))

Value of b :  0
Accuracy:  0.626953125
Value of b :  1
Accuracy:  0.626953125
Value of b :  2
Accuracy:  0.626953125
Value of b :  3
Accuracy:  0.626953125
Value of b :  4
Accuracy:  0.626953125
Value of b :  5
Accuracy:  0.626953125
Value of b :  6
Accuracy:  0.626953125
Value of b :  7
Accuracy:  0.626953125
Value of b :  8
Accuracy:  0.626953125
Value of b :  9
Accuracy:  0.626953125
Value of b :  10
Accuracy:  0.626953125
Value of b :  11
Accuracy:  0.626953125
Value of b :  12
Accuracy:  0.626953125
Value of b :  13
Accuracy:  0.62890625
Value of b :  14
Accuracy:  0.634765625
Value of b :  15
Accuracy:  0.638671875
Value of b :  16
Accuracy:  0.642578125
Value of b :  17
Accuracy:  0.65234375
Value of b :  18
Accuracy:  0.658203125
Value of b :  19
Accuracy:  0.666015625
Value of b :  20
Accuracy:  0.66796875
Value of b :  21
Accuracy:  0.68359375
Value of b :  22
Accuracy:  0.703125
Value of b :  23
Accuracy:  0.728515625
Value of b :  24
Accuracy:  0.763671875
Value of b :  25
